# .rubocop.yml

# AllCops configuration
AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "node_modules/**/*"
    - "bin/**/*"
    - "db/**/*"
    - "config/**/*"
    - "spec/requests/**/*"

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Lint/MissingSuper:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
