version: "3.9"
services:
  db:
    image: postgres:latest
    volumes:
      - merchants_portal_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/metrics
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
    env_file:
      - .env

volumes:
  merchants_portal_data:
