---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/merchants":
    get:
      summary: Retrieves all merchants by user_id
      tags:
      - Merchants
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Merchants found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                      required:
                      - id
                      - name
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/pipelines":
    get:
      summary: Retrieves all pipelines by user_id and merchant_id
      tags:
      - Pipelines
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      - name: merchant_id
        in: query
        required: true
        schema:
          type: string
      - name: active
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Active pipelines found
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
