---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/merchants":
    get:
      summary: Retrieves all merchants by user_id
      tags:
      - Merchants
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Merchants found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                      required:
                      - id
                      - name
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/partners":
    get:
      summary: Retrieves all partners by user_id and merchant_id
      tags:
      - Partners
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: user_id
        in: query
        required: true
        schema:
          type: string
      - name: merchant_id
        in: query
        required: true
        schema:
          type: string
      - name: active
        in: query
        required: false
        schema:
          type: boolean
      responses:
        '200':
          description: Active partners found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                        name:
                          type: string
                        about:
                          type: string
                        founded_in:
                          type: string
                        active:
                          type: boolean
                        stage:
                          type: string
                        categories:
                          type: array
                          items:
                            type: string
                        company_website:
                          type: string
                      required:
                      - id
                      - name
                      - about
                      - founded_in
                      - active
                      - stage
                      - categories
                      - company_website
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/partners/{id}":
    get:
      summary: Retrieves a partner by id
      tags:
      - Partners
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: merchant_id
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Partner found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                      about:
                        type: string
                      founded_in:
                        type: string
                      active:
                        type: boolean
                      stage:
                        type: string
                      categories:
                        type: array
                        items:
                          type: string
                      company_website:
                        type: string
                    required:
                    - id
                    - name
                    - about
                    - founded_in
                    - stage
                    - categories
                    - company_website
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Partner not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/pipelines/{id}/activate":
    post:
      summary: Activates a pipeline
      tags:
      - Pipelines
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Pipeline activated
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      merchant_id:
                        type: string
                        format: uuid
                      financial_institution_id:
                        type: string
                        format: uuid
                      partner:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          name:
                            type: string
                          about:
                            type: string
                          founded_in:
                            type: string
                          stage:
                            type: string
                          categories:
                            type: array
                            items:
                              type: string
                          company_website:
                            type: string
                        required:
                        - id
                        - name
                        - about
                        - founded_in
                        - stage
                        - categories
                        - company_website
                    required:
                    - id
                    - merchant_id
                    - financial_institution_id
                    - partner
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '404':
          description: Pipeline not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: Unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/pipelines":
    post:
      summary: Creates a pipeline
      tags:
      - Pipelines
      parameters:
      - name: access-token
        in: header
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Pipeline created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      merchant_id:
                        type: string
                        format: uuid
                      financial_institution_id:
                        type: string
                        format: uuid
                      partner:
                        type: object
                        properties:
                          id:
                            type: string
                            format: uuid
                          name:
                            type: string
                          about:
                            type: string
                          founded_in:
                            type: string
                          stage:
                            type: string
                          categories:
                            type: array
                            items:
                              type: string
                          company_website:
                            type: string
                        required:
                        - id
                        - name
                        - about
                        - founded_in
                        - stage
                        - categories
                        - company_website
                    required:
                    - id
                    - merchant_id
                    - financial_institution_id
                    - partner
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '400':
          description: Invalid parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                merchant_id:
                  type: string
                  format: uuid
                financial_institution_id:
                  type: string
                  format: uuid
              required:
              - merchant_id
              - financial_institution_id
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: localhost:3000
